all : allway 4way 8way direct
.PHONY : all
 
allway : all.cpp
	g++ -o allway all.cpp
4way : 4way.cpp
	g++ -o 4way 4way.cpp
8way : 8way.cpp
	g++ -o 8way 8way.cpp
direct : direct.cpp
	g++ -o direct direct.cpp
